### PR TITLE
Some cleanup and abstraction of state implementation

### PR DESCRIPTION
**Pull request by richcarl**

### CODE REVIEW

**Comment by jj1bdx** [comment]
@dgud Could you give us your thought on this code? I think you don't want to put another .hrl file in OTP;  I think the bottom line is whether using a tuple is faster than using a list for the internal state.

**Comment by richcarl** [comment]
I moved the definitions to the hrl file in order to be able to use them in the test suite, but then I never actually wrote any tests that needed to access the definitions directly. They could be moved back into the .erl file if you prefer.

**Comment by richcarl** [comment]
But in general, if you decide to use an "exotic" representation like cons cells for pairs, it's a good idea to at least use macros to abstract out the implementation, so that you don't make mistakes like the one with commas instead of vertical bar, and so that you can test that the code passes all tests both with the straightforward tuple representation and with the exotic representation. Then you know that you haven't hard coded any stuff that makes silly assumptions.

**Comment by dgud** [comment]
I did the optimization and @jj1bdx missed some of it in his merge, I do not think it is that "exotic" and
the type is specified to be a:
-type exsplus_state() :: nonempty_improper_list(uint58(), uint58()).

**Comment by richcarl** [comment]
I'm just saying that if you don't use macros, you can expect more bugs like that one in the future. Too easy to miss when you review the code, and too hard to know at a glance whether a hard-coded [_|_] should be part of a list or if it's really a state record.

**Comment by jj1bdx** [comment]
I think the patch's abstraction is legit and acceptable, but I also think it's up to @dgud whether to put the patch into rand.erl.

Also, the current code in 

https://github.com/jj1bdx/exsplus116/blob/ba2429466925b1baeb5a81d183b67e092c548994/src/exsplus116.erl#L49L71

already has all the necessary type definitions, and is identical to

https://github.com/dgud/otp/blob/401bf07f5908137cde206f2f755af83c9a7ff71e/lib/stdlib/src/rand.erl#L248L271

right now.

**Comment by dgud** [comment]
Ok, will think about it but @richcarl I still want you to review my branch, I value your opinions.

**Comment by jj1bdx** [comment]
@richcarl I also suggest you to help reviewing rand.erl; it's going to be a part of OTP 18.0.

**Comment by richcarl** [comment]
OK, the new OTP rand branch is a lot more ambitious, with multiple algorithms, and I guess it's pretty much write-once code, so it might not be worth trying to do this sort of future-proofing of the code.

**Comment by richcarl** [comment]
Related: I had an idea about adding a kind of portable random pool server to Erlang's kernel, based on the following simple piece of code: "rndbit() -> timer:sleep(1), element(3, os:timestamp()) rem 2." A simple visual test, generating a png with random bits produced this way, shows apparent true noise, at least on a Linux machine.

Such a server could be used  to supply seeds to other processes, by maintaining a small pool of truly random bits, mixing them with a good RNG sequence to avoid running out of numbers under high load. It wouldn't take a lot of code to implement this. But if you think that hashing the node/pid, taking the system time, and using the new unique_integer stuff is enough for automatic seeding, you might not need this.

**Comment by jj1bdx** [comment]
@richcarl: the entropy gathering code will be an interesting one, for an environment which OpenSSL or crypto is not available, though it's out of scope from this repository.

**Comment by richcarl** [comment]
Yes, I just took the opportunity to mention the idea here with both you and Dan present. The work would be done in another branch for the OTP repo.

**Comment by dgud** [comment]
The idea with the automatic seed is to give a decent seed and a fast and
decent algorithm for normal usage, like select which process to add work to
and so on. Using a static seed such as in random forced the user to check
if a seed was set and then call seed if not. Crypto can be used to set the
seed or to generate numbers directly as I do in the test code.

mån 4 maj 2015 22:39 Richard Carlsson notifications@github.com skrev:

**Pull request closed without merging**
